/**:
  ros__parameters:
    debug_mode: false
    has_static_tf_only: false
    rosbag_replay: false
    rosbag_length: 20.0
    maximum_queue_size: 5
    timeout_sec: 0.2
    is_motion_compensated: true
    publish_synchronized_pointcloud: true
    keep_input_frame_in_synchronized_pointcloud: true
    publish_previous_but_late_pointcloud: false
    synchronized_pointcloud_postfix: pointcloud
    input_twist_topic_type: twist
    input_topics: [
                    "/sensing/lidar/top/pointcloud", # unknown timestamp
                    "/sensing/lidar/left/pointcloud", # unknown timestamp
                    "/sensing/lidar/right/pointcloud", # unknown timestamp
                    "/sensing/lidar/rear/pointcloud", # unknown timestamp
                ]
    output_frame: base_link
    lidar_timestamp_offsets: [0.0, 0.02, 0.02, 0.02] # unknown offset
    lidar_timestamp_noise_window: [0.01, 0.01, 0.01, 0.01]
